# Generated by Django 2.0.5 on 2018-10-15 15:19

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_str', models.CharField(max_length=7, verbose_name='年月')),
                ('number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '时间分组',
                'verbose_name_plural': '时间分组',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
