# Generated by Django 2.1.2 on 2018-11-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181107_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='推荐'),
        ),
    ]
