# Generated by Django 2.1.2 on 2018-11-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181108_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='null.png', null=True, upload_to='media/blog_list/%Y/%m', verbose_name='展示图片'),
        ),
    ]
