# Generated by Django 2.1.2 on 2018-11-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181108_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='avatar/%Y/%m', verbose_name='头像'),
        ),
    ]
