# Generated by Django 2.1.2 on 2018-12-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181119_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='个人简历')),
                ('resume', models.FileField(upload_to='resume', verbose_name='简历')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
            },
        ),
    ]
